### ISSUE TITLE
Html not open in local url in chrome

### ISSUE THREAD

**Issue by play123** [akella/fake3d#4]
Sample give errors while open index page locally in chrome browser. Please help I need to open sample locally. Firefox working fine.

**Comment by akella** [comment]
you need to run a local server to see animation

**Comment by play123** [comment]
Sorry sir but I need to run in android device. And there is no local server so any other  help would be appreciated.

**Comment by akella** [comment]
You have to have a local or other server to run the code in this repo in a browser. I am not android developer so i cant help you with running it on android.

**Comment by play123** [comment]
Thanks for quick reply and amazing demo tamplate

**Comment by random-yang** [comment]
> Sorry sir but I need to run in android device. And there is no local server so any other help would be appreciated.

You can run this project at your pc/mac with local server. Then your pc/mac is a server. Your Android phone can access the serve by at the same wifi.
