### ISSUE TITLE
Vertical tilt not workings in Mobile

### ISSUE THREAD

**Issue by play123** [akella/fake3d#6]
Hi sir, horizontal movement working on device but vertical tilt effect not working. I also try with increasing tilt effect value but that also not work. I also open and check your demo link but that's also not working.

**Comment by akella** [comment]
accelerometer access  has been disabled in ios, mb thats the reason?

**Comment by play123** [comment]
I'm using the android device and I also try with facebook photo that also works fine. also, horizontal scrolling works fine. the only issue is the vertical tilt effect not work.
